services:
  hudson-news-bot:
    build:
      context: .
      dockerfile: Containerfile
    container_name: hudson-news-bot
    env_file:
      - .env
    tmpfs:
      - /tmp
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
      # Mount config directory for custom configurations
      - ./config:/app/config:ro
      # Mount database
      - ./data/:/app/data
    restart: unless-stopped
    command:
      # sleep infinity
      ["hudson-news-bot", "--log-level", "DEBUG"]

networks:
  default:
    name: hudson-news-bot-network
