services:
  hudson-news-bot:
    build:
      context: .
      dockerfile: Containerfile
    container_name: hudson-news-bot
    env_file:
      - .env
    tmpfs:
      - /tmp
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
      # Mount config directory for custom configurations
      - ./config:/app/config:ro
      # Mount Claude CLI config for authentication persistence
      - ./config/claude/:/home/app/.claude
      - ./config/mcp.json:/app/.mcp.json
    restart: unless-stopped
    command:
      sleep infinity
      # [
      #   "uv",
      #   "run",
      #   "python",
      #   "-m",
      #   "hudson_news_bot.main",
      #   "--log-level",
      #   "DEBUG",
      #   "--dry-run",
      # ]
